### ISSUE TITLE
since a while new nuget versions are released

### ISSUE THREAD

**Issue by redxeagle** [ferventcoder/nuget-gem#12]
Can I get new releases of this nuget gem?

Or should I made a pull request?

Greetings Daniel

**Comment by wallymathieu** [comment]
I can fix it tonight.

**Comment by redxeagle** [comment]
Sounds great.
Direct to: v5.5.1 of nuget?

**Comment by wallymathieu** [comment]
https://rubygems.org/gems/nuget/versions/5.5.1
