### ISSUE TITLE
Later version of NuGet.exe ?

### ISSUE THREAD

**Issue by wallymathieu** [ferventcoder/nuget-gem#2]
Hi any plans to change update the version of NuGet.exe ?

Br Oskar

**Comment by ferventcoder** [comment]
@danielmarbach Do you want to handle the updates?

**Comment by danielmarbach** [comment]
@ferventcoder Just pushed https://rubygems.org/gems/nuget/versions/2.8.60717.93

**Comment by danielmarbach** [comment]
should we build one which auto downloads the latest?

**Comment by wallymathieu** [comment]
Thanks for the new version!

**Comment by wallymathieu** [comment]
It would be sweet if the gem could download the latest version of nuget.
The [documentation](https://docs.nuget.org/consume/command-line-reference) mentions:

```
nuget update -Self
```

Is it kosher to have a globally installed gem with a new version of nuget though? I like how [paket](https://github.com/fsprojects/Paket) solves it (you but the binary in a folder .paket with gitignore on the binary).

**Comment by ferventcoder** [comment]
I'm all for automating the process.
