### ISSUE TITLE
Downloading nuget

### ISSUE THREAD

**Issue by wallymathieu** [ferventcoder/nuget-gem#4]
Perhaps something like this to automate the process of downloading nuget?

```
require 'net/http'
require 'net/https'

def download(serverName, srcPath, destPath)
    http = Net::HTTP.new(serverName,443)
    http.use_ssl = true
    # Might need to do this on windows:
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new(srcPath)

    f = open(destPath, "wb")

    begin
        http.request(request) do |resp| 
            resp.read_body do |segment|
                f.write(segment)
            end
        end
    ensure
        f.close
    end
end
#https://api.nuget.org/downloads/nuget.exe
download("api.nuget.org", "/downloads/nuget.exe", "./nuget.exe")
```

**Comment by ferventcoder** [comment]
Gems are point in time, this doesn't seem very point in time.

**Comment by ferventcoder** [comment]
@wallymathieu or is this for getting it down to package? 

I think this could be used to get the nuget package, then unzip it and you have the right nuget.exe for the gem version.

**Comment by wallymathieu** [comment]
I thought for building the gem once there is a new version of nuget available.

**Comment by ferventcoder** [comment]
Why don't we adjust it so it gets the latest version of the nuget package, evaluates the version from the package and plugs that into the gem version, then unpacks it and grabs the exe and then creates the gem from that?

**Comment by wallymathieu** [comment]
Sounds like a nice way!

**Comment by ferventcoder** [comment]
If you are interesting in filing a PR, that would be pretty swank!

**Comment by wallymathieu** [comment]
I'll try to get some time for it!
