### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by wallymathieu** [ferventcoder/nuget-gem#5]
Could you make a release of this package so that I can use it on *nix?

**Comment by ferventcoder** [comment]
I can make you a maintainer - provide your rubygems.org username and I can hook you up here as well.

**Comment by wallymathieu** [comment]
Hi, that would be sweet. My rubygems.org username is:
[wallymathieu](https://rubygems.org/profiles/wallymathieu)

**Comment by ferventcoder** [comment]
You are now an owner - https://rubygems.org/gems/nuget

**Comment by wallymathieu** [comment]
Thanks!

**Comment by wallymathieu** [comment]
I'll fix the issue!

**Comment by wallymathieu** [comment]
There is a release out. It should be possible to use nuget wrapper on *nix.
